name: Build, Test, and Deploy .NET 8 Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [8.0.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Publish build artifacts
        if: success()
        run: |
          mkdir -p artifacts
          find . -type d -name 'Release' -exec cp -r {}/. artifacts/ \;
        shell: bash

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: artifacts/

      - name: Publish test results
        if: success()
        run: |
          mkdir -p test-results
          find . -type d -name 'TestResults' -exec cp -r {}/. test-results/ \;
        shell: bash

      - name: Upload test results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t xaprun/aj-aspnetapp-alpine-k8s-gh:v0.9-test .
          docker push xaprun/aj-aspnetapp-alpine-k8s-gh:v0.9-test